apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gmk1c9q9r-python
  janus-idp.io/tekton: gmk1c9q9r-python
  backstage.io/kubernetes-id: gmk1c9q9r-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gmk1c9q9r-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
