apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gmk1c9q9r-python 
  janus-idp.io/tekton: gmk1c9q9r-python
  backstage.io/kubernetes-id: gmk1c9q9r-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gmk1c9q9r-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  