apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: gmk1c9q9r-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:86506d68bb2a2a5ea71881e2a68e48cb7c0c705a@sha256:d189054a9e35bbe25d217c40cb0b1f2cc5dc33e44a445a9e3195f06c6852d40d
          name: container-image
